
// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
var Verifier = artifacts.require('Verifier');
var { proof, inputs, wrongInputs } = require('./proof.json');

// Test verification with correct proof
// - use the contents from proof.json generated from zokrates steps
// Test verification with incorrect proof
contract('Verification', accounts => {
    account_one = accounts[0];
})
describe('Test Square Verification', function () {
    beforeEach(async function () {
        this.contract = await Verifier.new({ from: account_one });
    })

    it('correct proof', async function () {
        const result = await this.contract.verifyTx.call(proof.a, proof.b, proof.c, inputs);
        assert.equal(result, true)
    })
    it('wrong proof', async function () {
        const result = await this.contract.verifyTx.call(proof.a, proof.b, proof.c, wrongInputs);
        assert.equal(result, false)
    })
});
